apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: python3-container
    purpose: testing
  name: python3-container
  namespace: smart-selenium
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: python3-container
      purpose: testing
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: python3-container
        purpose: testing
    spec:
      containers:
      - command:
        - sleep
        - infinity
        image: python:3.6-slim
        imagePullPolicy: IfNotPresent
        name: python3
        resources:
          requests:
            cpu: 100m
            memory: 100Mi

